### ISSUE TITLE
Accuracy Bug

### ISSUE THREAD

**Issue by igor9silva** [Euphe/dungeon_bot#2]
There is probably a bug about accuracy.

I joined a lobby where a guy simply could not hit any monsters, every single attack of him was missed.

The game said that:
>Strengh = Defense/Attack
>Dexterity = Speed/Accuracy
>Intelligence = Level Up speed/Critical Chance
>Vitality = Health Points

And here are his stats:
```
Honk. lvl 1
----
Characteristics:
| Strength:8 (8)
| Dexterity:8 (8)
| Vitality:6 (6)
| Intelligence:1 (1)

Health:
| 84/84
Energy:
| 8/8, regen per turn: 2
Exp:
| 100/400
Average defence, evasion:
| 1, 29
Average accuracy:
| 19
Tags:
| animate, humanoid, human
Modifiers:
| 
Abilities:
| smash(club)
Equipment:
| Primary weapon: club |acc:2d6/dmg:2d5|.
Level perks:
|
```

**Comment by Euphe** [comment]
Actually accuracy relies on intelligence too. 

The basic accuracy formula is:
base_accuracy = diceroll( str(int(2*self.characteristics["intelligence"])) + "d" + str(2*self.characteristics["dexterity"] ))

Basically the guy had a basic accuracy of  2d8. 

Thats a problem with the description of characteristics, thanks for pointing it out.

**Comment by amPerl** [comment]
closed, description improved in 9d22aa4789103e1ca55534664a7abd905760f939

**Comment by glukki** [comment]
Hmm, not sure if I understand this right, but it looks like dexterity isn't used in code, but mentioned in formula, here for example: https://github.com/Euphe/dungeon_bot/blob/master/dungeon_bot/abilities.py#L540
```
class Cut(Ability):
	"""
	Cutting attack for swords, daggers, anything bladed.
	Effective against unarmored oponents, mediocore against armored oponents. 
	High chance to hit.
	Higher chance to hit big and slow oponents.
	chance to hit = accuracy * dexterity  - target_evasion - is_small * target_evasion * 2 - is_quick * target_evasion * 2 + is_big * target_evasion * 2 + is_slow * target_evasion * 2
	dmg = weapon_dmg * strength - defence * 1.5 - is_armored * defence * 2 - is_heavy_armored * defence * 3
	avg chance to hit = 55
	avg dmg = ?
	chance to cause "bleeding" = ?
	"""
	// ...
	@staticmethod
	def get_chance_to_hit(user, target, weapon):
		is_small = int("small" in target.tags)*2
		is_quick = int("quick" in target.tags)*2
		is_big = int("big" in target.tags)*3
		is_slow = int("slow" in target.tags)*3
		evasion = target.evasion
		accuracy = user.get_accuracy(weapon)
		dexterity = user.characteristics["dexterity"]

		chance_to_hit = clamp(accuracy - evasion, 5, 95 )

		return chance_to_hit
```
Is everything fine here?

**Comment by amPerl** [comment]
Yes, that code uses get_accuracy, which uses dexterity.
See: https://github.com/Euphe/dungeon_bot/blob/2336688398e5ca09f02f5bcad1cfe68ab216dfe4/dungeon_bot/creatures.py#L154

**Comment by glukki** [comment]
Oh, cool, thx! :)
