### ISSUE TITLE
Lobby: Error on chat message with spaces

### ISSUE THREAD

**Issue by glukki** [Euphe/dungeon_bot#3]
`say hello world` — leads to error
`say hello.world` — works fine

**Comment by Euphe** [comment]
https://i.gyazo.com/5d6323aacad6e3d0f47d65c9db83336d.png
I dont see the issue.

**Comment by glukki** [comment]
![screen shot 2015-08-06 at 23 34 46](https://cloud.githubusercontent.com/assets/140462/9122764/d21f138a-3c93-11e5-8a5a-4460fbf7f4a0.png)

**Comment by Euphe** [comment]
will fix

**Comment by Euphe** [comment]
fixed in the last version

**Comment by amPerl** [comment]
closed, Euphe fixed in 1e18bb58ce8afd4efd1ed12b436ccee71deff709
