### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by Ecorrales** [Euphe/dungeon_bot#4]
While in the inventory, after an item drop, the game should display the refreshed list of items. 
Just a sugerence..

**Comment by Euphe** [comment]
What do you mean by "refreshed"? Doesn't it get sorted?

**Comment by Ecorrales** [comment]
after you drop an item, the items get sorted again but you cant see it and, on the previous list of items 21 was another dagger, but now that dagger is the 20, if you erased the number 19.. 

if you drop the item 21 is no longer the same item as when your see it the last time. 

Soo, if you list again after the item droping you will see the new item sort. 
This is for people with larger inventory
![image](https://cloud.githubusercontent.com/assets/9013279/9126176/5ffec812-3c67-11e5-8527-de290704fd12.png)

**Comment by Euphe** [comment]
Yeah I thought about it as a problem. Most likely we will either implement an inventory limit of 20 items.
Also I think a good idea would be to have unique letters assigned to each item that dont change when the list of items changes.

**Comment by Ecorrales** [comment]
You could achieve this by not sending automaticly to the inventary the earned items, instead put a list with the winned items and a numer to select wich one you wanna save.. And instead of showing the items by defeated monster, they could be saved to a temporal variable that catch all winned items..

And showed when the combat finishes, also it could be relacionated to the player if he gets  offline or kicked by an error to the lobby, all the items he already won would be available to him on the lobby..

Just saying..
