### ISSUE TITLE
Make sweep skill for blunt weapons

### ISSUE THREAD

**Issue by Ecorrales** [Euphe/dungeon_bot#5]
You could make a sweep attack for blunt weapons!

**Comment by Euphe** [comment]
Will do!

**Comment by Ecorrales** [comment]
Nice! i got bugged inside a lobby 
![image](https://cloud.githubusercontent.com/assets/9013279/9147144/57872f1c-3d20-11e5-8df0-d8d233c07b7c.png)

**Comment by Euphe** [comment]
Thanks for reporting. It deserves a new issue though.
But we caught that bug recently. It will be fixed in the next update. As of now your empty lobby terminate in 3 minutes.
